modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="eyelibnetwork"
version="${mod_version}"
displayName="Eyelib Network"
authors="${mod_authors}"
description='''Eyelib network transport layer.'''

[[dependencies.eyelibnetwork]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.eyelibnetwork]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
