modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="eyelibmaterial"
version="${mod_version}"
displayName="Eyelib Material"
authors="${mod_authors}"
description='''Bedrock material definitions and GL state management for Eyelib.'''

[[dependencies.eyelibmaterial]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.eyelibmaterial]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
