modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="eyelibtrack"
version="${mod_version}"
displayName="Eyelib Track"
authors="${mod_authors}"
description='''ItemStack tracking and per-instance animation state for Eyelib.'''

[[dependencies.eyelibtrack]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.eyelibtrack]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
