modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="eyelibattachment"
version="${mod_version}"
displayName="Eyelib Attachment"
authors="${mod_authors}"
description='''Typed data attachment contracts and stream codec utilities for Eyelib.'''

[[dependencies.eyelibattachment]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.eyelibattachment]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
