modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="eyelibbehavior"
version="${mod_version}"
displayName="Eyelib Behavior"
description="${mod_description}"
authors="${mod_authors}"
