modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="eyelibbridge"
version="${mod_version}"
displayName="Eyelib Bridge"
authors="${mod_authors}"
description='''MC/Forge bridge adapters for Eyelib domain modules.'''

[[dependencies.eyelibbridge]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.eyelibbridge]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
